"""
Agentic Layer Metrics

Memory flow metrics including:
- Vectorize (Embedding) metrics
- Rerank metrics
- Retrieve pipeline metrics
- Memorize pipeline metrics
"""

from .vectorize_metrics import (
    VECTORIZE_REQUESTS_TOTAL,
    VECTORIZE_DURATION_SECONDS,
    VECTORIZE_BATCH_SIZE,
    VECTORIZE_FALLBACK_TOTAL,
    VECTORIZE_ERRORS_TOTAL,
    VECTORIZE_TOKENS_TOTAL,
)

from .rerank_metrics import (
    RERANK_REQUESTS_TOTAL,
    RERANK_DURATION_SECONDS,
    RERANK_DOCUMENTS_TOTAL,
    RERANK_FALLBACK_TOTAL,
    RERANK_ERRORS_TOTAL,
)

from .retrieve_metrics import (
    RETRIEVE_REQUESTS_TOTAL,
    RETRIEVE_DURATION_SECONDS,
    RETRIEVE_RESULTS_COUNT,
    RETRIEVE_STAGE_DURATION_SECONDS,
    RETRIEVE_ERRORS_TOTAL,
)

from .memorize_metrics import (
    MEMORIZE_REQUESTS_TOTAL,
    MEMORIZE_DURATION_SECONDS,
    MEMORIZE_MESSAGES_TOTAL,
    MEMORIZE_ERRORS_TOTAL,
    BOUNDARY_DETECTION_TOTAL,
    MEMCELL_EXTRACTED_TOTAL,
    MEMORY_EXTRACTION_STAGE_DURATION_SECONDS,
    MEMORY_EXTRACTED_TOTAL,
    EXTRACT_MEMORY_REQUESTS_TOTAL,
    EXTRACT_MEMORY_DURATION_SECONDS,
    # Utility functions
    get_space_id_for_metrics,
    get_raw_data_type_label,
)

__all__ = [
    # Vectorize metrics
    'VECTORIZE_REQUESTS_TOTAL',
    'VECTORIZE_DURATION_SECONDS',
    'VECTORIZE_BATCH_SIZE',
    'VECTORIZE_FALLBACK_TOTAL',
    'VECTORIZE_ERRORS_TOTAL',
    'VECTORIZE_TOKENS_TOTAL',
    
    # Rerank metrics
    'RERANK_REQUESTS_TOTAL',
    'RERANK_DURATION_SECONDS',
    'RERANK_DOCUMENTS_TOTAL',
    'RERANK_FALLBACK_TOTAL',
    'RERANK_ERRORS_TOTAL',
    
    # Retrieve metrics
    'RETRIEVE_REQUESTS_TOTAL',
    'RETRIEVE_DURATION_SECONDS',
    'RETRIEVE_RESULTS_COUNT',
    'RETRIEVE_STAGE_DURATION_SECONDS',
    'RETRIEVE_ERRORS_TOTAL',
    
    # Memorize metrics
    'MEMORIZE_REQUESTS_TOTAL',
    'MEMORIZE_DURATION_SECONDS',
    'MEMORIZE_MESSAGES_TOTAL',
    'MEMORIZE_ERRORS_TOTAL',
    
    # Boundary detection metrics
    'BOUNDARY_DETECTION_TOTAL',
    'MEMCELL_EXTRACTED_TOTAL',
    
    # Memory extraction metrics
    'MEMORY_EXTRACTION_STAGE_DURATION_SECONDS',
    'MEMORY_EXTRACTED_TOTAL',
    'EXTRACT_MEMORY_REQUESTS_TOTAL',
    'EXTRACT_MEMORY_DURATION_SECONDS',
]

