"""Main timeline renderer for macro message flow."""

from __future__ import annotations

import plotly.graph_objects as go
import streamlit as st

from config import COLOR_BY_TYPE, NODES_PER_ROW
from data_engine.parser import GraphRecord
from utils.geometry import (
    build_consecutive_edges,
    build_node_positions,
    clip_edge_ends,
    compute_session_orthogonal_polygon,
    polygon_points_to_path,
)
from utils.graph_render import (
    arrow_symbol,
    extract_selected_points,
    format_hover_value,
    pick_interaction_payload,
    wrap_hover_text,
)
from utils.session_state import set_expanded_subgraph, set_highlight_node


def _segment_visibility(
    src_id: str,
    dst_id: str,
    active_neighbors: set[str],
    *,
    edge_id: str,
    selected_edge_id: str | None,
) -> str:
    """Return the visibility state of one macro edge segment.

    Args:
        src_id (`str`):
            Source message ID.
        dst_id (`str`):
            Target message ID.
        active_neighbors (`set[str]`):
            Node IDs that should stay highlighted.
        edge_id (`str`):
            Unique macro edge ID in `<source_id>-><target_id>` format.
        selected_edge_id (`str | None`):
            Currently expanded macro edge ID.

    Returns:
        `str`:
            One of `"dim"` or `"active"`.
    """
    if selected_edge_id and edge_id != selected_edge_id:
        return "dim"
    if active_neighbors and not ({src_id, dst_id} & active_neighbors):
        return "dim"
    return "active"


def _build_session_ranges(
    graph: GraphRecord,
    index_by_message_id: dict[str, int],
) -> list[tuple[str, list[int]]]:
    """Collect message indices for each session in display order.

    Args:
        graph (`GraphRecord`):
            Parsed graph record whose sessions should be mapped to timeline indices.
        index_by_message_id (`dict[str, int]`):
            Message ID to display index mapping built from `graph.messages`.

    Returns:
        `list[tuple[str, list[int]]]`:
            Pairs of session ID and message indices in display order.
    """
    session_ranges: list[tuple[str, list[int]]] = []
    for session in graph.sessions:
        indices = [index_by_message_id[m.message_id] for m in session.messages]
        if indices:
            session_ranges.append((session.session_id, indices))
    return session_ranges


def _edge_hover_text(edge_id: str, src_id: str, dst_id: str) -> str:
    """Build hover text for one macro timeline edge."""
    return (
        f"<br><b>edge_id</b>: {edge_id}"
        + f"<br><b>source_id</b>: {src_id}"
        + f"<br><b>target_id</b>: {dst_id}"
    )


def render_timeline_plot(graph: GraphRecord) -> None:
    """Render the macro session timeline for one parsed graph.

    Args:
        graph (`GraphRecord`):
            Parsed graph record shown in the current page.

    Returns:
        `None`:
            This function renders directly into the current Streamlit container.
    """
    st.subheader("Macro Flow")
    st.caption("Click legend categories to filter visible message nodes.")

    if not graph.messages:
        st.info("This graph has no message nodes.")
        return

    message_ids = [m.message_id for m in graph.messages]
    positions = build_node_positions(len(graph.messages))
    edges = build_consecutive_edges(len(graph.messages))
    index_by_message_id = {message_id: i for i, message_id in enumerate(message_ids)}

    highlighted_id = st.session_state.get("current_highlight_node_id")
    highlight_mode = st.session_state.get("current_highlight_mode", "neighbor")
    selected_edge_id = st.session_state.get("current_expanded_subgraph_id")
    active_neighbors = set()
    if highlighted_id and highlighted_id in index_by_message_id and highlight_mode == "neighbor":
        highlight_index = index_by_message_id[highlighted_id]
        active_neighbors = {highlighted_id}
        if highlight_index > 0:
            active_neighbors.add(message_ids[highlight_index - 1])
        if highlight_index + 1 < len(message_ids):
            active_neighbors.add(message_ids[highlight_index + 1])
    elif highlighted_id and highlight_mode == "node_only":
        active_neighbors = {highlighted_id}

    fig = go.Figure()
    # Draw session containers as orthogonal polygons generated by geometry util.
    for session_id, indices in _build_session_ranges(graph, index_by_message_id):
        polygon = compute_session_orthogonal_polygon(
            indices,
            nodes_per_row=NODES_PER_ROW,
            padding_x=0.30,
            padding_y=0.30,
            connector_width_ratio=0.30,
        )
        path = polygon_points_to_path(polygon)
        if not path:
            continue
        fig.add_shape(
            type="path",
            path=path,
            line=dict(color="rgba(16,185,129,0.7)", width=1.4, dash="solid"), # line
            fillcolor="rgba(16,185,129,0.06)",
            layer="below",
        )

        label_anchor = min(polygon, key=lambda p: (p.y, p.x))
        fig.add_annotation(
            x=label_anchor.x + 8,
            y=label_anchor.y + 10,
            text=f"{session_id}",
            showarrow=False,
            xanchor="left",
            yanchor="top",
            font=dict(size=10, color="#065F46"),
        )

    # Draw each arrow segment independently so no visual long-strip linkage.
    arrow_x: list[float] = []
    arrow_y: list[float] = []
    arrow_symbols: list[str] = []
    arrow_opacity: list[float] = []
    arrow_custom: list[str] = []
    arrow_hover: list[str] = []

    hit_x: list[float] = []
    hit_y: list[float] = []
    hit_custom: list[str] = []
    hit_hover: list[str] = []

    for edge in edges:
        src_id = message_ids[edge.src_index]
        dst_id = message_ids[edge.dst_index]
        edge_id = f"{src_id}->{dst_id}"
        state = _segment_visibility(
            src_id,
            dst_id,
            active_neighbors,
            edge_id=edge_id,
            selected_edge_id=selected_edge_id,
        )

        x0, y0, x1, y1 = clip_edge_ends(edge.src.x, edge.src.y, edge.dst.x, edge.dst.y, gap=50.0) # arrow-node gap
        opacity = 0.2 if state == "dim" else 1.0
        edge_hover = _edge_hover_text(edge_id, src_id, dst_id)
        fig.add_trace(
            go.Scattergl(
                x=[x0, x1],
                y=[y0, y1],
                mode="lines",
                line=dict(color=f"rgba(107,114,128,{opacity})", width=5),
                hoverinfo="skip",
                showlegend=False,
            )
        )

        arrow_x.append(x1)
        arrow_y.append(y1)
        arrow_symbols.append(arrow_symbol(x1 - x0, y1 - y0))
        arrow_opacity.append(opacity)
        arrow_custom.append(f"edge|{edge_id}")
        arrow_hover.append(edge_hover)

        # Add invisible hit points along each edge to improve click accuracy.
        for t in (0.2, 0.5, 0.8):
            hx = x0 + (x1 - x0) * t
            hy = y0 + (y1 - y0) * t
            hit_x.append(hx)
            hit_y.append(hy)
            hit_custom.append(f"edge|{edge_id}")
            hit_hover.append(edge_hover)

    fig.add_trace(
        go.Scattergl(
            x=hit_x,
            y=hit_y,
            mode="markers",
            marker=dict(size=24, color="rgba(0,0,0,0.001)"),
            customdata=hit_custom,
            hovertemplate="%{hovertext}<extra></extra>",
            hovertext=hit_hover,
            showlegend=False,
        )
    )

    fig.add_trace(
        go.Scattergl(
            x=arrow_x,
            y=arrow_y,
            mode="markers",
            marker=dict(size=12, color="#111827", symbol=arrow_symbols, opacity=arrow_opacity), # arrow size
            customdata=arrow_custom,
            hovertemplate="%{hovertext}<extra></extra>",
            hovertext=arrow_hover,
            showlegend=False,
        )
    )

    # Draw nodes grouped by category so Plotly legend can filter them.
    category_nodes: dict[str, list[dict[str, Any]]] = {}

    for i, msg in enumerate(graph.messages):
        p = positions[i]
        opacity = 1.0
        if active_neighbors and msg.message_id not in active_neighbors:
            opacity = 0.2

        category_nodes.setdefault(msg.type, []).append(
            {
                "x": p.x,
                "y": p.y,
                "color": COLOR_BY_TYPE.get(msg.type, "#9CA3AF"),
                "opacity": opacity,
                "custom": f"node|{msg.message_id}",
                "text": msg.message_id,
                "hover": (
                    f"<b>message_id</b>: {msg.message_id}"
                    + f"<br><b>type</b>: {msg.type}"
                    + f"<br><b>text</b>: {wrap_hover_text(msg.text)}"
                    + f"<br><b>create_at</b>: {msg.create_at}"
                    + f"<br><b>session_id</b>: {msg.session_id}"
                    + f"<br><b>metadata</b>: {wrap_hover_text(format_hover_value(msg.metadata), width=100)}"
                ),
            }
        )

    for category in sorted(category_nodes):
        items = category_nodes[category]
        fig.add_trace(
            go.Scattergl(
                x=[item["x"] for item in items],
                y=[item["y"] for item in items],
                mode="markers+text",
                marker=dict(
                    size=28,
                    color=[item["color"] for item in items],
                    opacity=[item["opacity"] for item in items],
                    line=dict(color="#1F2937", width=1.5),
                ),
                text=[item["text"] for item in items],
                textposition="top center",
                customdata=[item["custom"] for item in items],
                hovertemplate="%{hovertext}<extra></extra>",
                hovertext=[item["hover"] for item in items],
                name=category,
                legendgroup=f"cat::{category}",
                showlegend=True,
            )
        )

    row_count = max(1, (len(graph.messages) + NODES_PER_ROW - 1) // NODES_PER_ROW)
    figure_height = max(620, min(2200, 180 + row_count * 140))

    fig.update_layout(
        height=figure_height,
        margin=dict(l=10, r=10, t=20, b=10),
        xaxis=dict(showgrid=False, zeroline=False, visible=False),
        yaxis=dict(showgrid=False, zeroline=False, visible=False, autorange="reversed"),
        clickmode="event+select",
        dragmode="pan",
        showlegend=bool(category_nodes),
        legend=dict(
            x=0.01,
            y=0.99,
            xanchor="left",
            yanchor="top",
            bgcolor="rgba(255,255,255,0.88)",
            bordercolor="rgba(15,23,42,0.35)",
            borderwidth=1,
            font=dict(size=11),
            itemclick="toggleothers",
            itemdoubleclick="toggle",
        ),
        uirevision=graph.graph_id,
    )

    with st.container(height=800):
        event = st.plotly_chart(
            fig,
            width="stretch",
            key=f"timeline_plot_{graph.graph_id}",
            on_select="rerun",
            selection_mode=["points"],
        )

    points = extract_selected_points(event)
    if not points:
        return

    payload = pick_interaction_payload(points, preferred_kinds=["edge", "node"])
    if payload is None:
        return

    kind, value = payload
    if kind == "node":
        new_highlight = None if st.session_state.get("current_highlight_node_id") == value else value
        set_highlight_node(new_highlight, mode="node_only")
        st.session_state["current_expanded_subgraph_id"] = None
    elif kind == "edge":
        new_edge = None if st.session_state.get("current_expanded_subgraph_id") == value else value
        set_expanded_subgraph(new_edge)
        set_highlight_node(None, mode="neighbor")
    st.rerun()
